### ISSUE TITLE
Integration with Vuejs: not detecting translations

### ISSUE THREAD

**Issue by AkdM** [transifex/transifex-javascript#100]
Hi there,

I have a bunch of projects with Vuejs waiting to be translated by some translators.
I set up everything on one of them, however no translations are found when I run the CLI. It won't detect any translations in the template or script tags in a `.vue` file, even in a `.js`.

As it doesn't work out of the box, I created a quick plugin that works when I initialise, but does not detect any translations:

```
import Vue from 'vue'
import { tx, t } from '@transifex/native'

Vue.use({
  install (Vue) {
    Vue.tx = Vue.prototype.$tx = tx
    Vue.tx.init({
      token: '[REDACTED TOKEN]'
    })
    Vue.t = Vue.prototype.t = t
  }
})
```
My wish is obviously to use things like `this.t()` or something similar on a `<script>` tag, and `{{ t() }}` on a `<template>` tag.

In another file I set the lang with `setCurrentLocale`.

Any idea how I can localize my Vuejs app by using the cloud-based localization solution with Transifex?
Thanks!

**Comment by nbasili** [comment]
The issue is related to the fact that `@transifex/cli` is using Babel, doing AST analysis on the code, looking for `t` functions and locating phrases.

So for plain `.js` files it should work, if you are using the code as `t('Hello')` and not `this.t('Hello')`. As a matter of fact, `tx` and `t` are singleton objects, so no need to bind them to `this`.

I am not familiar with Vue, but I think we could probably investigate adding [vue-template-compiler](https://www.npmjs.com/package/vue-template-compiler) in the `@transifex/cli` package, and update it to be able to parse Vue templates but it will requiring some digging, or even better a full fledged `@transifex/vue` package. 

But in the meantime, one (intermediate) solution you can use to unblock you, is create a temporary `phrases.js` file and copy the phrases you want to push to Transifex like:

```
t('Hello');
t('Another phrase');
...
```

then, push the phrases using `npx txjs-cli push phrases.js`.

Assuming that the quick plugin you created works, you should see your templates translated when running the code.

**Comment by AkdM** [comment]
Thanks @nbasili! I will dig that.
I am surprised Transifex doesn't have a `@transifex/vue` package, as vue is pretty much very popular too!

Either way, thanks for your quick reply.
