### ISSUE TITLE
@transifex/react@2.3.0 useT not working.

### ISSUE THREAD

**Issue by shaaandi** [transifex/transifex-javascript#110]
Reproducable link: https://codesandbox.io/s/transifex-2-3-0-issues-x3gmx?file=/src/App.tsx

Behaviour:
the `useT` is not working at all for main and other sub instances and return empty string.
The `T` is working good for the main instance, but not for sub instance and just return the string un-translated. 

Please let me know if you can reproduce this by urself, otherwise, I will leave the reproduction link for all the issues here.

Ps. It would be great if you can reproduce it urself. Thanks.

**Comment by codegaze** [comment]
Hey @shaaandi , thanks for the feedback and for providing a sandbox!  

**About useT**, the way is used has changed after the release of the `v2.0.0` version of the library which included breaking changes ([full migration guide](https://github.com/transifex/transifex-javascript/blob/HEAD/UPGRADE_TO_V2.md))

Before v2.0.0
```
const str = useT(‘Hello world’);
```

After v2.0.0
```
const t = useT();
const str = t(‘Hello world’);
```

**About the second part regarding the instances** and subcomponents, we’d like some more information to reproduce this, since the sandbox you provided doesn’t have this case.

From what I understand though from your comment, it should be working, as you can see in this different sandbox I created. https://codesandbox.io/s/charming-pare-ig8vy?file=/src/index.js

Changing languages with the dropdown you can see that the content changes also for the sub-instances when there is content available. When content is not available, it will fallback to the source language. 
In this example for the sub-instance we have only the `Greek` language and you can see that "Hello world" has a different translation for the two instances.
